# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  # Add ntfs for the windows drive
  boot.supportedFilesystems = ["ntfs"];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/edb10dc6-ed89-4de1-8134-19d2d3d2ae0b";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F973-299B";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/35890a7f-446d-46f1-a913-33b8f8af1ad8";}
  ];

  fileSystems."/mnt/windows" = {
    device = "/dev/disk/by-uuid/6ABE472FBE46F35D";
    fsType = "ntfs-3g";
    options = ["rw" "uid=1000"];
  };

  fileSystems."/mnt/nas" = {
    device = "nas:/volume1/";
    fsType = "nfs";
    options = [
      # Dont automount, and disconnect after 600 seconds (10 mins)
      "x-systemd.automount"
      "noauto"
      "x-systemd.idle-timeout=600"
    ];
  };

  services.rpcbind.enable = true; # needed for NFS

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.logitech.wireless.enable = true;

  # Disable "high-resolution scrolling" for mx master
  environment.etc."libinput/local-overrides.quirks".text = ''
    [Logitech MX Master 3]
    MatchVendor=0x46D
    MatchProduct=0x4082
    AttrEventCode=-REL_WHEEL_HI_RES;-REL_HWHEEL_HI_RES;
  '';
}
